import SwiftUI

struct AboutView: View {
    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    VStack(alignment: .leading, spacing: 6) {
                        Text("Register Drop Counter")
                            .font(.title2.weight(.semibold))
                            .foregroundStyle(.white)
                        Text("Designed by Ronald Robbins Jr and SuperGrok")
                            .foregroundStyle(.white)
                        Text("Version \(AppModel.version)  (\(AppModel.releaseDate))")
                            .font(.caption.monospaced())
                            .foregroundStyle(.white.opacity(0.85))
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
                    .background(Theme.navy)

                    Group {
                        Text("Count a drawer")
                            .font(.headline)
                            .foregroundStyle(Theme.navyFg)
                        Text("Set the register base. Open a till (R1–R10). Tap the name to rename it. Type counts in the yellow cells with the number pad. After $100, Enter wraps back to pennies on the same till. Amount, Drop, and Left fill in. Left turns green when it equals the base.")
                            .foregroundStyle(Theme.ink)
                        Text("Drop slip prints a bag slip. Undo clear brings back the last drawer. History stores every clear.")
                            .foregroundStyle(Theme.ink)
                        Text("The drop")
                            .font(.headline)
                            .foregroundStyle(Theme.navyFg)
                        Text("$100, $50, $20, $10, $5, $2, $1, then quarters, dimes, nickels, rolls, pennies. Loose coins drop before rolls.")
                            .foregroundStyle(Theme.ink)
                        Text("Changelog")
                            .font(.headline)
                            .foregroundStyle(Theme.navyFg)
                        Text("v2.33.0  Till keeps the last drop. On counter and Cleared tonight show the deposit. Font list is every installed face. New cash-drawer icon.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.32.0  Help holds History, Stats for Nerds, and About. Stats lists the full History ledger.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.31.0  Visual Studio 2022 build compiles after the Windows dark-mode paint path.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.30.0  Windows 10 dark mode paints title bar, buttons, tabs, and lists.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.29.0  Options and About live under File.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.28.0  File > Stats for Nerds on the Windows desktop app.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.27.0  Current release on web, Windows, iPhone, Android, and C23.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.26.0  Dark mode is a night theme: carbon, teal, and amber.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.25.0  File > Stats for Nerds charts drop trends from History on the web app.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.24.0  Dark mode on desktop: gold count cells and readable amount columns.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.23.0  Header keeps File, Clear all, and Undo. Downloads live on About in the web app.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.22.0  Tab after $100 wraps to pennies on the same till.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.21.0  Current release on web, Windows, iPhone, Android, and C23.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.20.0  Sample drops do not write History snapshots.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.19.0  Sample drops stay under $6,000 per till.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.18.0  File > Load Sample Drops fills every till with random test counts.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.17.0  Drop slip shows drop total and left in drawer at the top.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.16.0  Web app — unzip and open index.html in any browser.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.15.0  Dark mode polish — count and amount cells go dark.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.14.1  Visual Studio build — History till selection and till-name editor.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.14.0  Dark mode on the Options tab.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.13.0  Star TSC100 drop slip — 80 mm / 42-column receipt.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.12.0  Android app (Kotlin + Jetpack Compose). Same drop math.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.11.0  ISO C23 console app with the same drop math. No C++.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.10.0  iPhone app (SwiftUI). Same drop math as Windows and the web counter.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.9.0  Named tills — tap R1–R10 to rename.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.8.0  Undo clear and printable drop slip.")
                            .foregroundStyle(Theme.ink)
                        Text("v2.7.0  Phone number pad and arrow-key navigation.")
                            .foregroundStyle(Theme.ink)
                    }
                    .padding(.horizontal)
                }
                .padding(.bottom, 24)
            }
            .background(Theme.sheet)
            .navigationTitle("About")
        }
    }
}
